import { VendorNode } from "./vendorTypes";
import { BrandNode } from "./brandTypes";
import { ModelNode } from "./modelTypes";

export type VehicleNode = {
  id: string;
  entryNo: string;
  vendor: Partial<VendorNode>;
  brand: Partial<BrandNode>;
  model: Partial<ModelNode>;
  trim: string;
  slug: string;
  yearOfManufacture: string;
  yearOfFirstRegistration: string;
  registered: string;
  registrationNo: string;
  condition: string;
  mileage: number;
  mileageMetric: string;
  transmissionType: string;
  fuelType: string;
  engineCapacity: number;
  exteriorColor: string;
  upholstery: string;
  images: string;
  status: string;
  viewingLocation: string;
  vehicleOriginCountry: string;
  engineType: string;
  driveType: string;
  vinNo: string;
  bodyType: string;
  interiorColor: string;
  steering: string;
  seats: number;
  doors: number;
  listingPrice: number;
  discountedPrice: number;
  discountAmount: number;
  allowedPaymentModes: string;
  offerType: string;
  features: string;
  views: number;
  extraInfo: string;
  reserved: string;
  sold: string;
  publishedAt: string;
  impressions: number;
  detailExpands: number;
  interested: number;
  vehicleVerified: string;
};

export type VehicleRowType = {
  cursor: string;
  node: VehicleNode;
};
